name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
      with:
        node-version: '18.19.0'

    - name: Cache Node.js modules
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn

    - name: Setup
      run: yarn build:setup

    - name: Setup xvfb
      run: xvfb-run -a yarn run vscode:prepublish 

    - name: Run xvfb test
      run: xvfb-run -a yarn test

    - name: Prettier
      run: yarn run prettier:check

    - name: Lint
      run: yarn run lint