name: CI

on:
  push:
    branches: [ main, beta, prerelease ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - run: yarn prepare-beta
        if: ${{ steps.extract_branch.outputs.branch == 'beta' }}
      - name: Publish to Visual Studio Marketplace
        if: ${{ steps.extract_branch.outputs.branch != 'prerelease' }}
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          yarn: true
      - name: Publish to Visual Studio Marketplace for pre-release
        if: ${{ steps.extract_branch.outputs.branch == 'prerelease' }}
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          yarn: true
          preRelease: true
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          yarn: true
