name: CI

on:
  push:
    branches: [ master, v3 ]
  pull_request:
    branches: [ master, v3 ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

#       - name: Publish to Open VSX Registry
#         uses: HaaLeo/publish-vscode-extension@v0
#         with:
#           pat: ${{ secrets.OPEN_VSX_TOKEN }}
