name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.19.0'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn

    - name: Setup
      run: yarn build:setup

    - name: Setup xvfb
      run: xvfb-run -a yarn run vscode:prepublish 

    - name: Run xvfb test
      run: xvfb-run -a yarn test

    - name: Prettier
      run: yarn run prettier:check

    - name: Lint
      run: yarn run lint