name: CI

on:
  push:
    branches: [ main, beta, prerelease ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # 4.4.0
        with:
          node-version: '22.13.0'
      - run: yarn
      - run: yarn build:setup
      - run: yarn prepare-beta
        if: ${{ steps.extract_branch.outputs.branch == 'beta' }}
      - run: xvfb-run -a yarn test
      - run: yarn run prettier:check
      - run: yarn run lint
      - name: Publish to Visual Studio Marketplace
        if: ${{ steps.extract_branch.outputs.branch != 'prerelease' }}
        uses: HaaLeo/publish-vscode-extension@v1.5.0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          yarn: true
      - name: Publish to Visual Studio Marketplace for pre-release
        if: ${{ steps.extract_branch.outputs.branch == 'prerelease' }}
        uses: HaaLeo/publish-vscode-extension@v1.5.0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          yarn: true
          preRelease: true
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          yarn: true
